// src/main/webapp/app/entities/client/update/client-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import * as dayjs from 'dayjs';
import { DATE_TIME_FORMAT } from 'app/config/input.constants';

import { IClient, Client } from '../client.model';
import { ClientService } from '../service/client.service';
import { IConnexion } from 'app/entities/connexion/connexion.model';
import { ConnexionService } from 'app/entities/connexion/service/connexion.service';

@Component({
  selector: 'jhi-client-update',
  templateUrl: './client-update.component.html',
})
export class ClientUpdateComponent implements OnInit {
  isSaving = false;

  connexionsCollection: IConnexion[] = [];

  editForm = this.fb.group({
    id: [],
    iDClient: [],
    dateAjout: [],
    nom: [],
    prenom: [],
    email: [],
    telephone: [],
    adresse: [],
    pays: [],
    codePostale: [],
    connexion: [],
  });

  constructor(
    protected clientService: ClientService,
    protected connexionService: ConnexionService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ client }) => {
      if (client.id === undefined) {
        const today = dayjs().startOf('day');
        client.dateAjout = today;
      }

      this.updateForm(client);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const client = this.createFromForm();
    if (client.id !== undefined) {
      this.subscribeToSaveResponse(this.clientService.update(client));
    } else {
      this.subscribeToSaveResponse(this.clientService.create(client));
    }
  }

  trackConnexionById(index: number, item: IConnexion): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IClient>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(client: IClient): void {
    this.editForm.patchValue({
      id: client.id,
      iDClient: client.iDClient,
      dateAjout: client.dateAjout ? client.dateAjout.format(DATE_TIME_FORMAT) : null,
      nom: client.nom,
      prenom: client.prenom,
      email: client.email,
      telephone: client.telephone,
      adresse: client.adresse,
      pays: client.pays,
      codePostale: client.codePostale,
      connexion: client.connexion,
    });

    this.connexionsCollection = this.connexionService.addConnexionToCollectionIfMissing(this.connexionsCollection, client.connexion);
  }

  protected loadRelationshipsOptions(): void {
    this.connexionService
      .query({ filter: 'client-is-null' })
      .pipe(map((res: HttpResponse<IConnexion[]>) => res.body ?? []))
      .pipe(
        map((connexions: IConnexion[]) =>
          this.connexionService.addConnexionToCollectionIfMissing(connexions, this.editForm.get('connexion')!.value)
        )
      )
      .subscribe((connexions: IConnexion[]) => (this.connexionsCollection = connexions));
  }

  protected createFromForm(): IClient {
    return {
      ...new Client(),
      id: this.editForm.get(['id'])!.value,
      iDClient: this.editForm.get(['iDClient'])!.value,
      dateAjout: this.editForm.get(['dateAjout'])!.value ? dayjs(this.editForm.get(['dateAjout'])!.value, DATE_TIME_FORMAT) : undefined,
      nom: this.editForm.get(['nom'])!.value,
      prenom: this.editForm.get(['prenom'])!.value,
      email: this.editForm.get(['email'])!.value,
      telephone: this.editForm.get(['telephone'])!.value,
      adresse: this.editForm.get(['adresse'])!.value,
      pays: this.editForm.get(['pays'])!.value,
      codePostale: this.editForm.get(['codePostale'])!.value,
      connexion: this.editForm.get(['connexion'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-client-heading" data-cy="ClientCreateUpdateHeading" jhiTranslate="jHipsterExerciseApp.client.home.createOrEditLabel">
        Create or edit a Client
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="jHipsterExerciseApp.client.iDClient" for="field_iDClient">I D Client</label>
          <input type="number" class="form-control" name="iDClient" id="field_iDClient" data-cy="iDClient" formControlName="iDClient" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="jHipsterExerciseApp.client.dateAjout" for="field_dateAjout">Date Ajout</label>
          <div class="d-flex">
            <input
              id="field_dateAjout"
              data-cy="dateAjout"
              type="datetime-local"
              class="form-control"
              name="dateAjout"
              formControlName="dateAjout"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="jHipsterExerciseApp.client.nom" for="field_nom">Nom</label>
          <input type="text" class="form-control" name="nom" id="field_nom" data-cy="nom" formControlName="nom" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="jHipsterExerciseApp.client.prenom" for="field_prenom">Prenom</label>
          <input type="text" class="form-control" name="prenom" id="field_prenom" data-cy="prenom" formControlName="prenom" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="jHipsterExerciseApp.client.email" for="field_email">Email</label>
          <input type="text" class="form-control" name="email" id="field_email" data-cy="email" formControlName="email" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="jHipsterExerciseApp.client.telephone" for="field_telephone">Telephone</label>
          <input type="number" class="form-control" name="telephone" id="field_telephone" data-cy="telephone" formControlName="telephone" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="jHipsterExerciseApp.client.adresse" for="field_adresse">Adresse</label>
          <input type="text" class="form-control" name="adresse" id="field_adresse" data-cy="adresse" formControlName="adresse" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="jHipsterExerciseApp.client.pays" for="field_pays">Pays</label>
          <input type="text" class="form-control" name="pays" id="field_pays" data-cy="pays" formControlName="pays" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="jHipsterExerciseApp.client.codePostale" for="field_codePostale"
            >Code Postale</label
          >
          <input
            type="number"
            class="form-control"
            name="codePostale"
            id="field_codePostale"
            data-cy="codePostale"
            formControlName="codePostale"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="jHipsterExerciseApp.client.connexion" for="field_connexion">Connexion</label>
          <select class="form-control" id="field_connexion" data-cy="connexion" name="connexion" formControlName="connexion">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="connexionOption.id === editForm.get('connexion')!.value?.id ? editForm.get('connexion')!.value : connexionOption"
              *ngFor="let connexionOption of connexionsCollection; trackBy: trackConnexionById"
            >
              {{ connexionOption.id }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/client/client-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="jHipsterExerciseApp.client.home.createOrEditLabel"
          data-cy="ClientCreateUpdateHeading"
          v-text="$t('jHipsterExerciseApp.client.home.createOrEditLabel')"
        >
          Create or edit a Client
        </h2>
        <div>
          <div class="form-group" v-if="client.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="client.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('jHipsterExerciseApp.client.addedDateTime')" for="client-addedDateTime"
              >Added Date Time</label
            >
            <div class="d-flex">
              <input
                id="client-addedDateTime"
                data-cy="addedDateTime"
                type="datetime-local"
                class="form-control"
                name="addedDateTime"
                :class="{ valid: !$v.client.addedDateTime.$invalid, invalid: $v.client.addedDateTime.$invalid }"
                :value="convertDateTimeFromServer($v.client.addedDateTime.$model)"
                @change="updateZonedDateTimeField('addedDateTime', $event)"
              />
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('jHipsterExerciseApp.client.lastName')" for="client-lastName">Last Name</label>
            <input
              type="text"
              class="form-control"
              name="lastName"
              id="client-lastName"
              data-cy="lastName"
              :class="{ valid: !$v.client.lastName.$invalid, invalid: $v.client.lastName.$invalid }"
              v-model="$v.client.lastName.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('jHipsterExerciseApp.client.firstName')" for="client-firstName">First Name</label>
            <input
              type="text"
              class="form-control"
              name="firstName"
              id="client-firstName"
              data-cy="firstName"
              :class="{ valid: !$v.client.firstName.$invalid, invalid: $v.client.firstName.$invalid }"
              v-model="$v.client.firstName.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('jHipsterExerciseApp.client.email')" for="client-email">Email</label>
            <input
              type="text"
              class="form-control"
              name="email"
              id="client-email"
              data-cy="email"
              :class="{ valid: !$v.client.email.$invalid, invalid: $v.client.email.$invalid }"
              v-model="$v.client.email.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('jHipsterExerciseApp.client.phone')" for="client-phone">Phone</label>
            <input
              type="text"
              class="form-control"
              name="phone"
              id="client-phone"
              data-cy="phone"
              :class="{ valid: !$v.client.phone.$invalid, invalid: $v.client.phone.$invalid }"
              v-model="$v.client.phone.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('jHipsterExerciseApp.client.adress')" for="client-adress">Adress</label>
            <input
              type="text"
              class="form-control"
              name="adress"
              id="client-adress"
              data-cy="adress"
              :class="{ valid: !$v.client.adress.$invalid, invalid: $v.client.adress.$invalid }"
              v-model="$v.client.adress.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('jHipsterExerciseApp.client.country')" for="client-country">Country</label>
            <input
              type="text"
              class="form-control"
              name="country"
              id="client-country"
              data-cy="country"
              :class="{ valid: !$v.client.country.$invalid, invalid: $v.client.country.$invalid }"
              v-model="$v.client.country.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('jHipsterExerciseApp.client.postalCode')" for="client-postalCode"
              >Postal Code</label
            >
            <input
              type="text"
              class="form-control"
              name="postalCode"
              id="client-postalCode"
              data-cy="postalCode"
              :class="{ valid: !$v.client.postalCode.$invalid, invalid: $v.client.postalCode.$invalid }"
              v-model="$v.client.postalCode.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('jHipsterExerciseApp.client.connection')" for="client-connection"
              >Connection</label
            >
            <select class="form-control" id="client-connection" data-cy="connection" name="connection" v-model="client.connection">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="client.connection && connectionOption.id === client.connection.id ? client.connection : connectionOption"
                v-for="connectionOption in connections"
                :key="connectionOption.id"
              >
                {{ connectionOption.id }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.client.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./client-update.component.ts"></script>
